reset
col1 = "#159027"; col2 = "#c11b1b"; col3 = "#b3aa5"; col4 = "#ffb000"; col5 = "#7f3fb6"; col6 = "#3f81b6"
set auto x
set yrange [0:maxy]
set style data histogram
set style histogram rowstacked
set style fill solid
set boxwidth 0.9
set grid ytics
set xtic scale 0
set key left top
set ylabel 'Time (cycles)'
set xlabel '# Applications'
set title title

plot input_file using \
    2:xtic(1) ti col fc rgb col1, \
    '' u 4 ti col fc rgb col2

set terminal pdf
set output output_file
replot
